// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login";
  };
  "./users/add1.jsx": {
    id: "users/add1";
    page: "/";
  };
  "./login/login.jsx": {
    id: "login/login";
    page: "/login";
  };
};